export const userConstants = {
  USER_AUTH_REQUEST: 'USER_AUTH_REQUEST',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_FAILURE: 'USER_AUTH_FAILURE',
  GREETINGS_FLAG_REQUEST: 'GREETINGS_FLAG_REQUEST',
  GREETINGS_FLAG_SUCCESS: 'GREETINGS_FLAG_SUCCESS',
  USER_AUTH_OTP_VERIFY_REQUEST: 'USER_AUTH_OTP_VERIFY_REQUEST',
  USER_AUTH_OTP_VERIFY_SUCCESS: 'USER_AUTH_OTP_VERIFY_SUCCESS',
  USER_AUTH_OTP_VERIFY_FAILURE: 'USER_AUTH_OTP_VERIFY_FAILURE',
  USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
};
